version: '3'

services:
  web:
    image: hapi-example
    build: .
    depends_on:
      - mongo
    ports:
      - '10001:10001'
    volumes:
      - .:/apphapi
      - /apphapi/node_modules

  mongo:
    image: mongo
    expose:
      - '27017'
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hapi-example
      MONGO_INITDB_DATABASE: hapi-example

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hapi-example
      POSTGRES_DATABASE: hapi-example

volumes:
  mongodata:
