version: '3'

services:
  postgres:
    image: postgres
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hapi-example
      MONGO_INITDB_DATABASE: hapi-example
